language: php

dist: trusty

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.php-cs-fixer

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash bin/deploy.sh

env:
  global:
    - secure: "L2Fk2prteOc0B0QOs29uw+/8mjf/3x3rVOmh1kQKk/wE3SiUX69shJVnN3fnyFlhSOxgru+qtZoBfwmrJQsFVCEjB0O+m01Mt7wswhpGKzLU6hDUL/Qc6YhV9lTOaKWRFUUg9bPHFcMq8WT0bXxv2bX162ERHG+H1m9WcSDDjBE="
