language: php

php:
#  - 5.4
# disabled because of symfony 3
  - 5.5
  - 5.6
#  - hhvm
# disabled hhvm because of a bug in 3.2.0 which is resolved in 3.3.0
# see: https://github.com/facebook/hhvm/issues/3932

addons:
  apt:
    packages:
      - git

install:
  - composer install

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash bin/deploy.sh

env:
  global:
    - secure: "L2Fk2prteOc0B0QOs29uw+/8mjf/3x3rVOmh1kQKk/wE3SiUX69shJVnN3fnyFlhSOxgru+qtZoBfwmrJQsFVCEjB0O+m01Mt7wswhpGKzLU6hDUL/Qc6YhV9lTOaKWRFUUg9bPHFcMq8WT0bXxv2bX162ERHG+H1m9WcSDDjBE="
