language: php

php:
  - 5.4
  - 5.5
  - 5.6
#  - hhvm
# disabled hhvm because of a bug in 3.2.0 which is resolved in 3.3.0
# see: https://github.com/facebook/hhvm/issues/3932

install:
  - composer install

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
